"""initial schema

Revision ID: 2161a4cb7176
Revises: 
Create Date: 2025-08-05 00:57:38.171655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2161a4cb7176'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcdonald_agent_session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('chat_conversation', sa.Text(), nullable=True),
    sa.Column('order_detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('agent_sessions_pkey'))
    )
    op.drop_table('mcdonald_agent_session')
    # ### end Alembic commands ###
